
# vim: ft=make noexpandtab

CHECK_C_FILES := \
   check/check.c \
   check/chkmfmt.c

CFLAGS_CHECK := -Isrc -DMAUG_OS_UNIX -DMAUG_NO_RETRO -DDEBUG -DDEBUG_LOG -DDEBUG_THRESHOLD=1

mcheck: $(addprefix obj/,$(subst .c,.o,$(CHECK_C_FILES)))
	$(CC) -o $@ $^ $(shell pkg-config --libs check)

obj/%.o: %.c
	mkdir -p $(dir $@)
	$(CC) -c -o $@ $(CFLAGS_CHECK) $(shell pkg-config --cflags check) $<

clean:
	rm -rf mcheck obj

