---
name: Documentation
on:
  push:
    branches: [master]

jobs:
  build-documentation:
    runs-on: docker
    container:
      image: docker.io/library/debian:bookworm
    steps:
    - name: Install prerequisites
      run: |
        apt update && apt install -y git openssh-client

    - name: Checkout actions
      run: |
        git clone ${{ github.server_url }}/indigoparadox/actions actions

    - name: Checkout maug
      run: |
        git clone ${{ github.server_url }}/${{ github.repository }} app

    - name: Run doxygen for Interfinity Dynamics
      uses: ./actions/doxygen

    - name: Push docs to Interfinity Dynamics
      uses: ./actions/pages
      with:
        docs-remote-repo: ssh://git@forgejo.interfinitydynamics.info:22022/indigoparadox/maug

    - name: Push docs to Codeberg
      uses: ./actions/pages
      with:
        docs-remote-repo: ssh://git@codeberg.org/indigoparadox/maug

