
#ifndef RETROKEY_H
#define RETROKEY_H

#define RETROFLAT_KEYTABLE( f ) \
   f( RETROFLAT_KEY_GRAVE ) \
   f( RETROFLAT_KEY_SLASH ) \
   f( RETROFLAT_KEY_UP ) \
   f( RETROFLAT_KEY_DOWN ) \
   f( RETROFLAT_KEY_RIGHT ) \
   f( RETROFLAT_KEY_LEFT ) \
   f( RETROFLAT_KEY_BKSP ) \
   f( RETROFLAT_KEY_A ) \
   f( RETROFLAT_KEY_B ) \
   f( RETROFLAT_KEY_C ) \
   f( RETROFLAT_KEY_D ) \
   f( RETROFLAT_KEY_E ) \
   f( RETROFLAT_KEY_F ) \
   f( RETROFLAT_KEY_G ) \
   f( RETROFLAT_KEY_H ) \
   f( RETROFLAT_KEY_I ) \
   f( RETROFLAT_KEY_J ) \
   f( RETROFLAT_KEY_K ) \
   f( RETROFLAT_KEY_L ) \
   f( RETROFLAT_KEY_M ) \
   f( RETROFLAT_KEY_N ) \
   f( RETROFLAT_KEY_O ) \
   f( RETROFLAT_KEY_P ) \
   f( RETROFLAT_KEY_Q ) \
   f( RETROFLAT_KEY_R ) \
   f( RETROFLAT_KEY_S ) \
   f( RETROFLAT_KEY_T ) \
   f( RETROFLAT_KEY_U ) \
   f( RETROFLAT_KEY_V ) \
   f( RETROFLAT_KEY_W ) \
   f( RETROFLAT_KEY_X ) \
   f( RETROFLAT_KEY_Y ) \
   f( RETROFLAT_KEY_Z ) \
   f( RETROFLAT_KEY_0 ) \
   f( RETROFLAT_KEY_1 ) \
   f( RETROFLAT_KEY_2 ) \
   f( RETROFLAT_KEY_3 ) \
   f( RETROFLAT_KEY_4 ) \
   f( RETROFLAT_KEY_5 ) \
   f( RETROFLAT_KEY_6 ) \
   f( RETROFLAT_KEY_7 ) \
   f( RETROFLAT_KEY_8 ) \
   f( RETROFLAT_KEY_9 ) \
   f( RETROFLAT_KEY_TAB ) \
   f( RETROFLAT_KEY_SPACE ) \
   f( RETROFLAT_KEY_ESC ) \
   f( RETROFLAT_KEY_ENTER ) \
   f( RETROFLAT_KEY_HOME ) \
   f( RETROFLAT_KEY_END ) \
   f( RETROFLAT_KEY_DELETE ) \
   f( RETROFLAT_KEY_PGUP ) \
   f( RETROFLAT_KEY_PGDN ) \
   f( RETROFLAT_KEY_SEMICOLON ) \
   f( RETROFLAT_KEY_PERIOD ) \
   f( RETROFLAT_KEY_COMMA ) \
   f( RETROFLAT_KEY_EQUALS ) \
   f( RETROFLAT_KEY_DASH ) \
   f( RETROFLAT_KEY_BACKSLASH ) \
   f( RETROFLAT_KEY_QUOTE ) \
   f( RETROFLAT_KEY_BRACKETL ) \
   f( RETROFLAT_KEY_BRACKETR ) \
   f( RETROFLAT_KEY_INSERT ) \

#endif /* !RETROKEY_H */

